:numbered:

= RHPAM (Business Central + KIE Server + Postgres) Provisioning

.Prerequisites:
* Log in into Openshift as cluster admin user.

== Integration with RH-SSO
As per the link:https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.3/html-single/deploying_a_red_hat_process_automation_manager_authoring_environment_on_red_hat_openshift_container_platform/index#environment-authoring-single-proc[Deploying a RH-PAM Authoring Env on RHT OCP], Business Central and KIE-Server can be secured via the _OpenID Connect_ protocol by integrating with RH-SSO.

This ansible optionally allows for the provisioning of Business Central and KIE-Server integrated with a previously configured RH-SSO.

The out-of-the-box defaults for integration with RH-SSO closely allign with an RH-SSO provisioned via link:https://github.com/gpe-mw-ansible-org/rh-sso-multi-realm/blob/master/README.adoc#kie-realm[rh-sso-multi-realm] ansible.

All of the default ansible variables needed for integrating with RH-SSO can be found in the following file of this project:  roles/openshift_rhpam_dev/defaults/main.yml .
The default values of these variables can all be over-written at the _ansible-playbook_ command line.


== Manage Sequence of PAM 7 Installs

NOTE: This approach is not applicable in a shared GPTE cluster such as na311.
Use only in a dedicated OCP cluster workshop environment:  ie:  https://labs.opentlc.com -> Services -> OPENTLC OpenShift Labs -> OpenShift Workshop Deployer

. Environment Variables
+
-----
# Using custom images for Business-Central and KIE Server.
# Specifically, the following are derived from RHT RHPAM 7.2.x images:
#   1) quay.io/btison/rhpam72-kieserver-openshift-gpte:1.1 
#   2) quay.io/btison/rhpam72-businesscentral-openshift-gpte:1.1
# The images are configured with users and groups required to support GPTE courses and labs.
use_custom_pam=true

seq_start=1     # specify first rhpam env to manage
seq_end=1       # specify last rhpam env to manage

-----

. Install
+
-----
$ ansible-playbook playbooks/install.yml \
    -e use_custom_pam=$use_custom_pam \
    -e seq_start=$seq_start \
    -e seq_end=$seq_end
-----

. Uninstall
+
-----
$ ansible-playbook playbooks/install.yml \
    -e ACTION=uninstall \
    -e seq_start=$seq_start \
    -e seq_end=$seq_end
-----


== Manage Individual Components of a Single PAM7 Install

. Shell Environment Variables
+
-----
# Using custom images for Business-Central and KIE Server.
# Specifically, the following are derived from RHT RHPAM 7.2.x images:
#   1) quay.io/btison/rhpam72-kieserver-openshift-gpte:1.1 
#   2) quay.io/btison/rhpam72-businesscentral-openshift-gpte:1.1
# The images are configured with users and groups required to support GPTE courses and labs.
use_custom_pam=true

# project names will be of convention: pam-7-tools-{{ guid }} and will be owned by {{ ocp_user }}
ocp_user=opentlcuser-redhat.com
guid=1234 

use_cluster_quota=true
kieserver_image_namespace=rhpam-dev-$guid
businesscentral_image_namespace=rhpam-dev-$guid
-----


. Provision PostgreSQL Admin Console
+
-----
$ ansible-playbook playbooks/pgadmin4.yml \
    -e ocp_user=$ocp_user \
    -e guid=$guid \
    -e use_cluster_quota=$use_cluster_quota
-----

. Provision Nexus
+
-----
$ ansible-playbook playbooks/nexus2.yml \
    -e ocp_user=$ocp_user \
    -e guid=$guid \
    -e use_cluster_quota=$use_cluster_quota
-----

. Provision PAM components
+
-----
$ ansible-playbook playbooks/rhpam_dev.yml \
    -e ocp_user=$ocp_user \
    -e guid=$guid \
    -e use_cluster_quota=$use_cluster_quota \
    -e kieserver_image_namespace=$kieserver_image_namespace \
    -e businesscentral_image_namespace=$businesscentral_image_namespace \
    -e use_custom_pam=$use_custom_pam
-----


