---

application_name: rhpam
businesscentral_application_name: "{{ application_name }}-bc"
kieserver_application_name: "{{ application_name }}-kieserver"

service_account: "{{ application_name }}-rhpamsvc"


businesscentral_image: rhpam-businesscentral-rhel8
businesscentral_image_tag: 7.6.0-2
businesscentral_image_namespace: openshift
business_central_cpu_request: 200m
businesscentral_memory_request: 1Gi
businesscentral_cpu_limit: 2000m
businesscentral_memory_limit: 3Gi
businesscentral_java_max_mem_ratio: 60
businesscentral_java_initial_mem_ratio: 0
businesscentral_gc_max_metaspace_size: 500
businesscentral_java_opts_append: "-Dorg.uberfire.nio.git.ssh.algorithm=RSA"
businesscentral_pvc_name: "{{ businesscentral_application_name }}-claim"
businesscentral_pvc_volume_capacity: "1Gi"
bc_template_yaml: rhpam-dev-business-central.yaml


businessmonitoring_application_name: "{{ application_name }}-monitoring"
businessmonitoring_image_namespace: openshift
businessmonitoring_image: rhpam-businesscentral-monitoring-rhel8
businessmonitoring_image_tag: 7.6.0-2
businessmonitoring_cpu_request: 200m
businessmonitoring_memory_request: 3Gi
businessmonitoring_cpu_limit: 2000m
businessmonitoring_memory_limit: 3Gi
businessmonitoring_java_max_mem_ratio: 60
businessmonitoring_java_initial_mem_ratio: 0
businessmonitoring_gc_max_metaspace_size: 500
businessmonitoring_java_opts_append: "-Dorg.uberfire.nio.git.ssh.algorithm=RSA"
businessmonitoring_pvc_name: "{{ businessmonitoring_application_name }}-claim"
businessmonitoring_pvc_volume_capacity: "1Gi"
bc_monitoring_template_yaml: rhpam-monitoring.yaml

kie_server_controller_prefer_kieserver_service: "false"
kie_server_controller_template_cache_ttl: "60000"
kie_workbench_controller_openshift_enabled: "false"

kieserver_image_namespace: openshift
kieserver_image: rhpam-kieserver-rhel8
kieserver_image_tag: 7.6.0-2

kieserver_cpu_request: 200m
kieserver_memory_request: 1Gi
kieserver_cpu_limit: 1000m
kieserver_memory_limit: 3Gi
kieserver_java_max_mem_ratio: 60
kieserver_java_initial_mem_ratio: 0
kieserver_gc_max_metaspace_size: 500

kie_admin_user: adminUser
kie_admin_password: admin1!
kieserver_controller_user: controllerUser
kieserver_controller_password: controller1!
kieserver_user: executionUser
kieserver_password: execution1!
kie_maven_user: adminUser
kie_maven_password: admin1!
kie_mbeans: enabled

kieserver_id: kieserver-dev

drools_server_filter_classes: true
kieserver_bypass_auth_user: false

kieserver_controller_protocol: ws
kieserver_host: "{{ kieserver_application_name }}"
kieserver_port: 8080
kieserver_protocol: http
ks_template_yaml: rhpam-dev-kieserver.yaml



custom_kieserver_image: rhpam-ks-apd
custom_kieserver_image_tag: 1.3
custom_businesscentral_image: rhpam-bc-apd
custom_businesscentral_image_tag: 1.3
custom_businessmonitoring_image: rhpam-monitoring-apd
customerbusinessmontoring_image_tag: 1.3

nexus_host: "{{ nexus_app }}.{{ project_nexus }}.svc"
nexus_port: 8081
nexus_path: content/groups/public/

postgresql_template: "{{ resources_dir }}/rhpam-dev-postgresql.yaml"
postgresql_application_name: "{{ application_name }}-postgresql"
postgresql_credentials_secret: "{{ postgresql_application_name }}"
postgresql_init_configmap: "{{ postgresql_application_name }}-init"
postgresql_pv_capacity: 5Gi
postgresql_version: 9.6
postgresql_is_namespace: openshift
postgresql_username: rhpam
postgresql_password: rhpam
postgresql_database: rhpam
postgresql_max_connections: 100
postgresql_max_prepared_transactions: 100
postgresql_memory_limit: 512Mi

psql_cpu_request: 250m
psql_memory_request: 256Mi
psql_cpu_limit: 500m
psql_memory_limit: 512Mi

use_custom_pam: false

PROMETHEUS_SERVER_EXT_DISABLED: true


# ##########   RH-SSO Integration    ###############

# Values below are set as per the default "kie-realm" provisioned from:
#   https://github.com/gpe-mw-ansible-org/rh-sso-multi-realm/blob/master/README.adoc#kie-realm

# Keep blank unless actually integrating with RH-SSO
# If integrating with RH-SSO, use a URL similar to the following:
#   https://sso-rhsso-sso0.apps-71b4.generic.opentlc.com/auth
rhsso_url: 
sso_realm: kie-realm
sso_disable_ssl_certificate_validation: "true"

business_central_sso_client: business-central
business_central_sso_secret: 252793ed-7118-4ca8-8dab-5622fa97d892
kie_server_sso_client: kie-server
kie_server_sso_secret: 252793ed-7118-4ca8-8dab-5622fa97d892

# The following will be used to create the above SSO clients in RH-SSO if they do not already exist in the {{ sso_realm }}.
sso_username: admin
sso_password: admin1234

###########################################################
