---

- name: install nexus
  import_role: 
    name: openshift_nexus2
  vars:
    ocp_project: "{{ project_tools }}"
    ocp_project_display_name: "{{ project_tools_display_name }}"
    ocp_project_desc: "{{ project_tools_desc }}"
    work_dir_name: nexus2
    resources_dir: "{{ resources_home_dir }}/nexus2"
  when: install_tools|bool
  
- name: install pgadmin4
  import_role: 
    name: openshift_pgadmin4
  vars:
    ocp_project: "{{ project_tools }}"
    ocp_project_display_name: "{{ project_tools_display_name }}"
    ocp_project_desc: "{{ project_tools_desc }}"
    work_dir_name: pgadmin4
    resources_dir: "{{ resources_home_dir }}/pgadmin4"
  when: install_tools|bool

- name: install load tester
  import_role:
    name: openshift_loadtester
  vars:
    ocp_project: "{{ project_tools }}"
    ocp_project_display_name: "{{ project_tools_display_name }}"
    ocp_project_desc: "{{ project_tools_desc }}"
    work_dir_name: loadtester
    resources_dir: "{{ resources_home_dir }}/loadtester"
  when: install_tools|bool

- name: install rhpam-dev
  import_role: 
    name: openshift_rhpam_dev
  vars:
    project_nexus: "{{ project_tools }}"
    ocp_project: "{{ project_rhpam }}"
    ocp_project_display_name: "{{ project_rhpam_display_name }}"
    ocp_project_desc: "{{ project_rhpam_desc }}"
    work_dir_name: rhpam-dev
    resources_dir: "{{ resources_home_dir }}/rhpam"    
